// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportationExceptionManagement.Infrastructure.Persistence;

#nullable disable

namespace TransportationExceptionManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransportationExceptionsDbContext))]
    [Migration("20260810125518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TransportationExceptionManagement.Domain.Entities.CaseNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransportationExceptionCaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransportationExceptionCaseId", "CreatedAtUtc");

                    b.ToTable("CaseNotes", (string)null);
                });

            modelBuilder.Entity("TransportationExceptionManagement.Domain.Entities.TransportationExceptionCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assignee")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationNode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("DueAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginNode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ResolvedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Assignee");

                    b.HasIndex("CaseReference")
                        .IsUnique();

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DueAtUtc");

                    b.HasIndex("ExceptionType");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.ToTable("TransportationExceptionCases", (string)null);
                });

            modelBuilder.Entity("TransportationExceptionManagement.Domain.Entities.CaseNote", b =>
                {
                    b.HasOne("TransportationExceptionManagement.Domain.Entities.TransportationExceptionCase", null)
                        .WithMany("Notes")
                        .HasForeignKey("TransportationExceptionCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransportationExceptionManagement.Domain.Entities.TransportationExceptionCase", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
